services:
  - type: web
    name: tg-dl-bot
    runtime: docker          # ← Fuerza Docker, ignora el entorno nativo de Render
    plan: free
    dockerfilePath: ./Dockerfile
    healthCheckPath: /health

    envVars:
      - key: API_ID
        sync: false
      - key: API_HASH
        sync: false
      - key: BOT_TOKEN
        sync: false
      - key: SESSION_STRING
        sync: false
      - key: CHUNK_SIZE
        value: "524288"
      - key: MAX_BATCH_SIZE
        value: "50"
      - key: PROGRESS_UPDATE_INTERVAL
        value: "3.0"
